version: "3"
services:
  # mysql
  mysql:
    container_name: mysql
    build:
      context: ./db/
      dockerfile: Dockerfile
    tty: true
    #volumes:
    #  - ./db/sql/:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root

  # React
  front:
    container_name: front
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ./frontend/src:/usr/src/app/src
      - ./frontend/public:/usr/src/app/public
    working_dir: /usr/src/app
    command: npm run start
    ports:
      - "3000:3000"
    depends_on:
      - back

  # Spring
  back:
    container_name: back
    build:
      context: ./backend/
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ./backend/REST/src:/usr/src/app/REST/src
    working_dir: /usr/src/app/REST
    command: sh -c  ./gradlew bootrun
    ports:
      - "8080:8080"
    depends_on:
      - mysql
